### ISSUE TITLE
Failure to compile with GHC 7.6 and GHC 7.8

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#150]
Travis is failing because it's not finding `(<$>)` automatically in the List module.

https://travis-ci.org/ivanperez-keera/dunai/jobs/591202899

```
src/Control/Monad/Trans/MSF/List.hs:20:39:
    Not in scope: `<$>'
    Perhaps you meant `<+>' (imported from Data.MonadicStreamFunction)
```
