### ISSUE TITLE
Tagged fails to compile with GHC 8.4

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#125]
This is the message on travis:
```
Control/Monad/SamplingMonad.hs:12:10: error:
    • Could not deduce (Semigroup (NextSample a))
        arising from the superclasses of an instance declaration
      from the context: Ord a
        bound by the instance declaration
        at Control/Monad/SamplingMonad.hs:12:10-39
    • In the instance declaration for ‘Monoid (NextSample a)’
   |
12 | instance Ord a => Monoid (NextSample a) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ivanperez-keera** [comment]
Now, this is annoying. The latest build fails due to ambiguity, but the operator is qualified:

```
Control/Monad/SamplingMonad.hs:30:17: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Data.Monoid.<>’
                             imported from ‘Data.Monoid’ at Control/Monad/SamplingMonad.hs:6:1-18
                          or ‘Sem.<>’
                             imported from ‘Data.Semigroup’ at Control/Monad/SamplingMonad.hs:10:1-28
   |
30 |   mappend = Sem.(<>)
   |               
```

It even calls it `Sem.(<>)`!!
