### ISSUE TITLE
`dunai`: failure to build with transformers >= 0.6

### ISSUE THREAD

**Issue by juhp** [ivanperez-keera/dunai#371]
For stackage nightly:
```
       Building library for dunai-0.11.0..
       [10 of 22] Compiling Control.Monad.Trans.MSF.List
       
       /var/stackage/work/unpack-dir/unpacked/dunai-0.11.0-5435c0e0ccd848461ead40b59dd4c8dd7f36a010ed3f10c6795e0c52f8e614b4/src/Control/Monad/Trans/MSF/List.hs:40:1: error:
           Could not find module ‘Control.Monad.Trans.List’
           Perhaps you meant
             Control.Monad.Trans.Has (needs flag -package-id has-transformers-0.1.0.4)
             Control.Monad.Trans.Cont (needs flag -package-id rerebase-1.20)
             Control.Monad.Trans.Cont (from transformers-0.6.1.0)
           Use -v (or `:set -v` in ghci) to see a list of the files searched for.
          |
       40 | import Control.Monad.Trans.List hiding (liftCallCC, liftCatch)
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ivanperez-keera** [comment]
The problem is not GHC 9.6 per se, but transformers 0.6, which removed `Control.Monad.Trans.List`.

**Comment by ivanperez-keera** [comment]
Closed as duplicate of #368 .
